In [2]:
print('ciao')

ciao


In [6]:
a = int(input("Enter a number a: "))
b = int(input("Enter a number b: "))

if a > b:
    print(f"{a} maggiore di {b}")
else:
    print(f"{b} maggiore di {a}")

4 maggiore di 3


In [9]:
lista = []
lista2 = [2,3]
stringa = ""

lista[:], lista2[1:4], stringa[1:2]

([], [3], '')

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [5]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4 ,3, 2, 1])

a > 5, np.any(a > 5), a[a > 5], np.all(a > 5)

(array([False, False, False, False, False,  True,  True,  True, False,
        False, False, False, False]),
 np.True_,
 array([6, 7, 6]),
 np.False_)

In [7]:
import random
import numpy as np

salary = [random.randint(100000, 150000) for num in range(10)]

salary

salary_array = np.array(salary)
salary_array

total_sum_salaries = np.sum(salary_array)
total_sum_salaries

product_salaries = np.prod(salary_array)
product_salaries


cumulative_sum_salaries = np.cumsum(salary_array)
cumulative_sum_salaries




array([ 113076,  248463,  355428,  476309,  594785,  729763,  844179,
        977313, 1125203, 1255727])